### ISSUE TITLE
Level problem with latest version

### ISSUE THREAD

**Issue by seanmcl** [robsimmons/agda-lib#2]
I just installed Agda:

    $ agda --version
    Agda version 2.4.2.3

and got the following error on load

    .../Lib/Level.agda:13,3-34
    Duplicate binding for built-in thing LEVEL, previous binding to
    .Agda.Primitive.Level
    when checking the pragma BUILTIN LEVEL Level

**Comment by robsimmons** [comment]
Huh! It works with 2.3.2.2, I'll try to upgrade and see if I can figure out what's wrong.

**Comment by mietek** [comment]
> A new module called `Agda.Primitive` has been introduced. This module
> is available to all users, even if the standard library is not used.
> Currently the module contains level primitives and their
> representation in Haskell when compiling with `MAlonzo`:
> 
> ```agda
> infixl 6 _⊔_
> 
> postulate
>   Level : Set
>   lzero : Level
>   lsuc  : (ℓ : Level) → Level
>   _⊔_   : (ℓ₁ ℓ₂ : Level) → Level
> 
> {-# COMPILED_TYPE Level ()      #-}
> {-# COMPILED lzero ()           #-}
> {-# COMPILED lsuc  (\_ -> ())   #-}
> {-# COMPILED _⊔_   (\_ _ -> ()) #-}
> 
> {-# BUILTIN LEVEL     Level  #-}
> {-# BUILTIN LEVELZERO lzero  #-}
> {-# BUILTIN LEVELSUC  lsuc   #-}
> {-# BUILTIN LEVELMAX  _⊔_    #-}
> ```
> 
> To bring these declarations into scope you can use a declaration
> like the following one:
> 
> ```agda
> open import Agda.Primitive using (Level; lzero; lsuc; _⊔_)
> ```
> 
> The standard library reexports these primitives (using the names
> `zero` and `suc` instead of `lzero` and `lsuc`) from the `Level` module.
> 
> Existing developments using universe polymorphism might now trigger
> the following error message:
> 
> ```
> Duplicate binding for built-in thing LEVEL, previous binding to
> .Agda.Primitive.Level
> ```
> 
> To fix this problem, please remove the duplicate bindings.
> 
> Technical details (perhaps relevant to those who build Agda
> packages):
> 
> The include path now always contains a directory `<DATADIR>/lib/prim`,
> and this directory is supposed to contain a subdirectory `Agda`
> containing a file `Primitive.agda`.
> 
> The standard location of `<DATADIR>` is system- and
> installation-specific.  E.g., in a `cabal --user` installation of
> `Agda-2.3.4` on a standard single-ghc Linux system it would be
> `$HOME/.cabal/share/Agda-2.3.4` or something similar.
> 
> The location of the `<DATADIR>` directory can be configured at
> compile-time using Cabal flags (`--datadir` and `--datasubdir`).
> The location can also be set at run-time, using the `Agda_datadir`
> environment variable.

**Comment by mietek** [comment]
Similarly:

> Builtin `ZERO` and `SUC` have been merged with `NATURAL`.
> 
> When binding the `NATURAL` builtin, `ZERO` and `SUC` are bound to the appropriate constructors automatically. This means that instead of writing
> 
> ```agda
> {-# BUILTIN NATURAL Nat #-}
> {-# BUILTIN ZERO zero #-}
> {-# BUILTIN SUC suc #-}
> ```
> 
> you just write
> 
> ```agda
> {-# BUILTIN NATURAL Nat #-}
> ```
